dependencies {
    // 프레젠테이션 계층 의존성
    implementation project(':module-common')
    implementation project(':module-domain')
    implementation project(':module-infrastructure')
    implementation project(':module-security')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.6'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.security:spring-security-core'
    implementation 'org.springframework.security:spring-security-oauth2-core'
    compileOnly 'org.springframework:spring-tx'
    compileOnly 'org.springframework.boot:spring-boot-starter-data-mongodb'
    compileOnly 'org.springframework.boot:spring-boot-starter-data-redis'
    compileOnly 'jakarta.persistence:jakarta.persistence-api'
}

bootJar {
    enabled = false
}

jar {
    enabled = true
}
