dependencies {
    // 실행 모듈 조립
    implementation project(':module-common')
    implementation project(':module-domain')
    implementation project(':module-infrastructure')
    implementation project(':module-presentation')

    // module-app 모듈에서 직접 사용하는 Spring Data 어노테이션
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    // Actuator (Health check, Metrics)
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    // Micrometer - Prometheus 메트릭 노출
    implementation 'io.micrometer:micrometer-registry-prometheus'

    // Runtime 의존성 (MySQL JDBC 드라이버)
    runtimeOnly 'com.mysql:mysql-connector-j'

    // Test
    testImplementation 'org.springframework.security:spring-security-test'
}

// module-app 모듈만 실행 가능한 JAR 생성
bootJar {
    enabled = true
}

jar {
    enabled = false
}
