apiVersion: 1

datasources:

  # Prometheus
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: POST

  # Loki
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: true
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          name: TraceID
          matcherRegex: '\[([a-f0-9]+),'
          url: '$${__value.raw}'

        - datasourceUid: tempo
          name: SpanID
          matcherRegex: ',([a-f0-9]+)\]'
          url: '$${__value.raw}'

  # Tempo
  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    editable: true
    jsonData:
      nodeGraph:
        enabled: true
      search:
        hide: false
