# 전역 설정
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  # 라벨
  external_labels:
    monitor: 'pinhouse-be-local'

# 스크랩핑
scrape_configs:

  # Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'prometheus:9090' ]
