dependencies {
    implementation project(':module-common')
    implementation project(':module-domain')
    implementation project(':module-infrastructure')
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-aop'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.springframework:spring-tx'
    compileOnly 'jakarta.persistence:jakarta.persistence-api'
    compileOnly 'org.springframework.data:spring-data-jpa'

    implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'

    testImplementation 'org.springframework.security:spring-security-test'
}

bootJar {
    enabled = false
}

jar {
    enabled = true
}
